// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjHZrYrevA-j00ucYeRXTprw-w8glE1c',
    appId: '1:860622105871:web:68743fa4c5f52ee271e27a',
    messagingSenderId: '860622105871',
    projectId: 'flashcard-quiz-635b1',
    authDomain: 'flashcard-quiz-635b1.firebaseapp.com',
    storageBucket: 'flashcard-quiz-635b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_EPWRLyr25Zbx_Py4qmPE9sTGqFb9sk',
    appId: '1:860622105871:android:389fc5eee2b967fc71e27a',
    messagingSenderId: '860622105871',
    projectId: 'flashcard-quiz-635b1',
    storageBucket: 'flashcard-quiz-635b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBet_gV_mH_DHG17t_GptWXcB3q58j4VQg',
    appId: '1:860622105871:ios:04816c9abdc19e2871e27a',
    messagingSenderId: '860622105871',
    projectId: 'flashcard-quiz-635b1',
    storageBucket: 'flashcard-quiz-635b1.firebasestorage.app',
    iosBundleId: 'com.example.quizProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBet_gV_mH_DHG17t_GptWXcB3q58j4VQg',
    appId: '1:860622105871:ios:04816c9abdc19e2871e27a',
    messagingSenderId: '860622105871',
    projectId: 'flashcard-quiz-635b1',
    storageBucket: 'flashcard-quiz-635b1.firebasestorage.app',
    iosBundleId: 'com.example.quizProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQjHZrYrevA-j00ucYeRXTprw-w8glE1c',
    appId: '1:860622105871:web:9114266cb022e62a71e27a',
    messagingSenderId: '860622105871',
    projectId: 'flashcard-quiz-635b1',
    authDomain: 'flashcard-quiz-635b1.firebaseapp.com',
    storageBucket: 'flashcard-quiz-635b1.firebasestorage.app',
  );
}
